// AUTH
export const AUTO_LOGIN_REQUEST = "AUTO_LOGIN_REQUEST";
export const AUTO_LOGIN_SUCCESS = "AUTO_LOGIN_SUCCESS";
export const AUTO_LOGIN_FAILURE = "AUTO_LOGIN_FAILURE";
export const AUTO_LOGIN_RESET = "AUTO_LOGIN_RESET";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGIN_RESET = "LOGIN_RESET";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

// THE GUARDIAN
export const THE_GUARDIAN_SEARCH_REQUEST = "THE_GUARDIAN_SEARCH_REQUEST";
export const THE_GUARDIAN_SEARCH_FINISHED = "THE_GUARDIAN_SEARCH_FINISHED";

export const GET_THE_GUARDIAN_CATEGORIES_REQUEST = "GET_THE_GUARDIAN_CATEGORIES_REQUEST";
export const GET_THE_GUARDIAN_CATEGORIES_FINISHED = "GET_THE_GUARDIAN_CATEGORIES_FINISHED";

// NEW YORK TIMES
export const NEW_YORK_TIMES_REQUEST = "NEW_YORK_TIMES_REQUEST";
export const NEW_YORK_TIMES_FINISHED = "NEW_YORK_TIMES_FINISHED";

export const GET_NEW_YORK_TIMES_CATEGORIES_REQUEST = "GET_NEW_YORK_TIMES_CATEGORIES_REQUEST";
export const GET_NEW_YORK_TIMES_CATEGORIES_FINISHED = "GET_NEW_YORK_TIMES_CATEGORIES_FINISHED";

// USER PREFERENCES
export const SAVE_PREFERRED_CATEGORIES_REQUEST = "SAVE_PREFERRED_CATEGORIES_REQUEST";
export const SAVE_PREFERRED_CATEGORIES_FINISHED = "SAVE_PREFERRED_CATEGORIES_FINISHED";

export const SET_CATEGORY_MODAL_VISIBLE = "SET_CATEGORY_MODAL_VISIBLE";

export const SET_CATEGORY_MODAL_CANCELED = "SET_CATEGORY_MODAL_CANCELED";
